name: CI-CD
on:
  push: 
    branches: ["main"]
  workflow_dispatch:   

jobs: 
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Construção da Imagem Docker e envio para Docker Hub
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            fernandoguara/review-filmes:v${{ github.run_number }}
            fernandoguara/review-filmes:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]    
    steps:
      - name: Checkout do código fonte
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-2
      - name: Configuração do kubeConfig
        run: aws eks update-kubeconfig --name aula-eks
      - name: Deploy do Kubernates  
      - uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: |
            fernandoguara/review-filmes:v${{ github.run_number }}
          
      
      
    
    
    
    
  
    
